site_name: excav PILOT
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/icon.png
  favicon: assets/icon.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  - print-site:
      path_to_pdf: "assets/anleitung_excav_pilot.pdf"

nav:
  - Startseite: index.md
  - Komponentenübersicht:
      - Gesamtsystem: Gesamtsystem/Gesamtsystem.md
      - GNSS-Sensor: GNSS-Sensor/GNSS-Sensor.md
      - LED-Anzeigekreuz: LED-Anzeigekreuz/LED-Anzeigekreuz.md
      - Tablet und Halterung: Tablet und Halterung/Tablet und Halterung.md
      - Basisstation: Basisstation/Basisstation.md
      - Messstab: Messstab/Messstab.md
      - Transportkoffer: Transportkoffer/Transportkoffer.md
      - Ladegerät: Ladegerät/Ladegerät.md
      - Metallrahmen: Metallrahmen/Metallrahmen.md

  - App:
      - Arbeitsansicht: Arbeitsansicht/Arbeitsansicht.md
      - Startmenü:
          - Geräte: Geräte/Geräte.md
          - NTRIP: NTRIP/NTRIP.md
          - Werkzeuge: Werkzeuge/Werkzeuge.md
          - Arbeitsplatz: Arbeitsplatz/Arbeitsplatz.md
      - Designmenü:
          - Übersicht: Übersicht/Übersicht.md
          - Koordinatensystem: Koordinatensystem/Koordinatensystem.md
          - Punkte: Punkte/Punkte.md
          - Linien: Linien/Linien.md
          - Kreise: Kreise/Kreise.md
          - Flächen: Flächen/Flächen.md
          - Baugrube: Baugrube/Baugrube.md
          - Bauplan: Bauplan/Bauplan.md
          - Gelände: Gelände/Gelände.md

  - Erste Schritte:
      - System aufbauen: System aufbauen/System aufbauen.md
      - System einrichten: System einrichten/System einrichten.md
      - Kalibrierung: Kalibrierung/Kalibrierung.md

  - Weitere Informationen:
      - Häufige Fragen: Häufige Fragen/Häufige Fragen.md
      - Fehlerbehebung: Fehlerbehebung/Fehlerbehebung.md
      - Sicherheitshinweise: Sicherheitshinweise/Sicherheitshinweise.md

extra_css:
  - styles.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
