site_name: excav pilot Bedienungsanleitung
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  palette:
    primary: custom
    - scheme: default
      toggle:
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        name: Switch to light mode



extra_css:
  - styles.css
