site_name: excav pilot Bedienungsanleitung
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode





extra_css:
  - styles.css
