site_name: excav PILOT
theme: 
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Willkommen: index.md
  - Geräteübersicht: uebersicht.md
  - Erste Schritte:
    - Aufbauen und Anbringen: erste_schritte/aufbauen.md
    - System einrichten: erste_schritte/einrichten.md
    - Erste Fläche abziehen: erste_schritte/flaeche.md
  - App:
    - Einrichtungsassistent: app/einrichtungsassistent.md
    - Arbeitsansicht: app/arbeitsansicht.md
    - Funktionen:
      - Übersicht: app/funktionen/uebersicht.md
      - Punkte und Strecken: app/funktionen/punkte.md
      - Flächen: app/funktionen/flaeche.md
      - Bauplan: app/funktionen/bauplan.md
      - Schaufeleinstellungen: app/funktionen/schaufeleinstellungen.md
      - Sonstige Einstellungen: app/funktionen/einstellungen.md
      - Protokoll und Status: app/funktionen/protokoll_status.md
  - Häufige Fragen: faqs.md
  - Fehlerbehebung: fehlerbehebung.md


extra_css:
  - styles.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
